name: Pull Request Build
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: git-crypt
          version: 1.0
          
      - name: Import GPG Key for git-crypt
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GIT_CRYPT_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          
      - name: Unlock encrypted files
        run: git crypt unlock
        
      - name: Prepare environment files
        run: |
          mkdir -p app/src/main/assets
          cp .env.dev app/src/main/assets/.env
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Grant gradle permissions
        run: chmod +x gradlew
        
      - name: Build debug APK
        run: ./gradlew assembleDebug --build-cache --parallel --daemon
        
