name: Android Modular Release Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      env-dir: ${{ steps.env-output.outputs.env-dir }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import GPG Key for git-crypt
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GIT_CRYPT_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install git-crypt
        run: |
          sudo apt-get update
          sudo apt-get install git-crypt -y

      - name: Unlock encrypted files
        run: git crypt unlock

      - name: Prepare environment files
        id: env-output
        run: |
          mkdir -p app/src/main/assets
          cp .env.dev app/src/main/assets/.env
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "env-dir=$(pwd)" >> $GITHUB_OUTPUT

      - name: Upload prepared workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Download workspace from setup
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode and create keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Build release and profile APKs
        run: |
          ./gradlew clean
          ./gradlew assembleRelease assembleProfile \
            -Pandroid.injected.signing.store.file=keystore.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: app/build/outputs/apk/**/*.apk

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          name: apks
          path: ./dist/apks

      - name: Create GitHub Release with APKs
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Release #${{ github.run_number }}"
          body: |
            Automated modular release.
            Includes signed and profiled APKs.
          files: ./dist/apks/**/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
